---
#Packages for LAMP
#
#
package_name:
  - apache2
  - mysql-server
  - php7.0-common
  - php7.0-mysql
  - libapache2-mod-php7.0
  - python-mysqldb
  - wget


#variable for mysql
mysql_db: "wordpress"
mysql_user: "user1"
mysql_password: "123456"
